name: Main
on:
  - pull_request
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo event: ${{github.event_name}}
          echo branch: ${{github.branch}}
          echo ref: ${{github.ref}}
  common:
    name: Dependencies, Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

  build-app:
    name: Build application
    needs:
      - common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node: ${{ matrix.node }}

      - name: Build
        uses: ./.github/actions/build-app

      - name: Save build directory
        uses: actions/upload-artifact@v3
        with:
          name: 'build-'
          path: "dist"
          if-no-files-found: error
          retention-days: 2

  deploy-to-heroku:
    name: Deploy to Heroku
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build-app
    uses: './.github/workflows/deploy-to-heroku.yml'
    with:
      node: 12
    secrets:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
